x = float(80)
y = float(74)
z = float(85)
a = float(77)
print("--- Your Score ---")
print("Foundation English :",x)
print("General Business   :",y)
print("Introduction to Computer Systems : ",z)
print("Computer Programming :",a)